name: autopep8
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8 
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --aggressive --exit-code --ignore E402 --exclude="./spack/var/spack/repos/builtin/packages/py-pyprecice/package.py" .
      - name: Fail if autopep8 made changes
        if: ${{ steps.autopep8.outputs.exit-code }} == 2
        run: exit 1
